import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.util.Random;

import javax.imageio.ImageIO;
import javax.media.jai.Histogram;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

import java.awt.*;

import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class StegoApp extends JFrame {
		
	public static BufferedImage coverImage, qrCode,
								oneBitStegoImage, threeBitStegoImage, fiveBitStegoImage,
								qrCodeOneBit, qrCodeThreeBit, qrCodeFiveBit;

	public static void main(String[] args) {
        try {
            // Payload.generateQRCodeImage("This is my first QR Code", 350, 350, Payload.QR_CODE_IMAGE_PATH);
        	coverImage = ImageIO.read(new File("assets/18.pgm"));
        	// Create stego image
        	LSB testingStego = new LSB(coverImage, 1, "Testing message", 250, 250);
			testingStego.embed();
			
			LSB oneBit = new LSB(coverImage, 1, UI.secretMessage, 512, 512);
			oneBit.embed();
			
			LSB threeBit = new LSB(coverImage, 3, UI.secretMessage, 512, 512);
			threeBit.embed();
			
			LSB fiveBit = new LSB(coverImage, 5, UI.secretMessage, 512, 512);
			fiveBit.embed();
			
			// Save stego image
			File stegofile = new File("OUTPUT/stego.png");
			ImageIO.write(testingStego.getStegoImage(), "png", stegofile);
			
			File coverfile = new File("OUTPUT/cover.png");
			ImageIO.write(coverImage, "png", coverfile);
			
			oneBitStegoImage = oneBit.getStegoImage();
			threeBitStegoImage = threeBit.getStegoImage();
			fiveBitStegoImage = fiveBit.getStegoImage();
			
			// Save qrcode before image
			Path path = FileSystems.getDefault().getPath("OUTPUT/qrCodeBefore.png");
	        MatrixToImageWriter.writeToPath(testingStego.getPayload(), "PNG", path);
			
			// Extract QR code
			qrCode = MatrixToImageWriter.toBufferedImage(oneBit.extract());
			
			qrCodeOneBit = MatrixToImageWriter.toBufferedImage(oneBit.extract());
			qrCodeThreeBit = MatrixToImageWriter.toBufferedImage(threeBit.extract());
			qrCodeFiveBit = MatrixToImageWriter.toBufferedImage(fiveBit.extract());
			
			// Save QR code after
			File qrfileafter = new File("OUTPUT/qrCodeAfter.png");
			ImageIO.write(qrCode, "png", qrfileafter);
            
			// Decode QR code and output message
            String decodedText = Payload.decodeQRCode(qrCode);
            if (decodedText == null) {
                System.out.println("No QR Code found in the image");
            } else {
                System.out.println("Decoded text = " + decodedText);
            }

            
        } catch (IOException e) {
            System.out.println("Could not generate QR Code or load image, IOException :: " + e.getMessage());
        }
        
		new StegoApp("StegoCompare");

    } // end main
	
	public StegoApp(String title) {
		super(title);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		UI mainPanel = new UI(null);
		this.add(mainPanel);
		this.pack();
		this.setLocationRelativeTo(null);
		this.setVisible(true);
			
	}
	
	public static BufferedImage getNewImage() throws IOException {
		BufferedImage newImage;
		int random = new Random().nextInt(19) + 1;
		newImage = ImageIO.read(new File("assets/" + random + ".pgm"));
		return newImage;	
	}
	


	
}
