/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class StegoAppTest {
//    @Test public void testSomeLibraryMethod() {
//        StegoApp classUnderTest = new StegoApp();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
}
